- lib/twilio/device.ts
- tests/integration/mutableOptions.ts
- tests/unit/device.ts
- [VBLOCKS-146](https://issues.corp.twilio.com/browse/VBLOCKS-146)
Fix double register during `Device.updateOptions`.
> [VBLOCKS-146] Fix double register during `Device.updateOptions`.

- README.md
PR in place of https://github.com/twilio/twilio-voice.js/pull/4
This adds a section for how to pull in the sdk code from github. Because the CDN is no longer available, we want to show an option for how to get the code without node or npm (for example, if someone is just testing the sdk with a server in a different language, and doesn't want to download node to run this).
> Add instructions to README for getting code from GitHub

- CHANGELOG.md
- lib/twilio/preflight/preflight.ts
#44 
Emit DOMException rather than DOMError
TODO: Update CHANGELOG after rebasing on master.
> GH44 VBLOCKS-471

- .gitignore
- lib/twilio/call.ts
- lib/twilio/device.ts
- lib/twilio/pstream.js
- lib/twilio/rtc/peerconnection.js
- lib/twilio/uuid.ts
- package.json
- tests/peerconnection.js
- tests/pstream.js
- tests/unit/call.ts
VBLOCKS-981 VBLOCKS-1093 | Updating eventing API per latest specs
> VBLOCKS-981 VBLOCKS-1093 | Updating eventing API per latest specs

- .gitignore
- CHANGELOG.md
- README.md
- lib/twilio/call.ts
- lib/twilio/device.ts
- lib/twilio/regions.ts
- tests/unit/device.ts
- tests/unit/regions.ts
Removed the region->edge mapping and now using the edge locations directly. Also removing Device.Options.region code paths since this options has been removed in 2.x
TODO: Add tests
> VBLOCKS-1086 Use voice-js DNS names directly

- lib/twilio/device.ts
- tests/unit/device.ts
The goal of this PR is to fix the issue described in [here](https://github.com/twilio/twilio-voice.js/issues/133)
When the user receives an incoming sound and calls `call.accept()` and just afterwards `call.disconnect`, the incoming sound keeps playing forever.
To overcome this issue, I just had to call `_maybeStopIncomingSound` which will stop the sound if there are any calls left.
> fix(incoming-sound): stop incoming sound when the call gets disconnected

- CHANGELOG.md
- lib/twilio/call.ts
- lib/twilio/device.ts
- tests/unit/call.ts
Some of the call methods that destroys the call such as `reject`and `ignore`, does not actually perform cleanups after they are invoked unlike disconnect method. This causes errors on future pstream events as described in #100 and jira ticket.
However, we don't want to cleanup on some, such as `ignore` method. If we perform cleanup, other clients who are also receiving the calls will get disconnected. But in the case of `reject`, this causes disconnection on all clients so it's ok to perform the cleanup process. This PR is adding that cleanup process on `reject`.
Additionally, I'm also …
> VBLOCKS-1371 | Remove handlers for rejected calls

- CHANGELOG.md
- lib/twilio/rtc/icecandidate.ts
- lib/twilio/rtc/stats.js
- tests/payloads/rtcstatsreport-edge.json
- tests/payloads/rtcstatsreport-with-transport.json
- tests/payloads/rtcstatsreport.json
- tests/spec/rtcicecandidates-with-transport.json
[VBLOCKS-1534](https://issues.corp.twilio.com/browse/VBLOCKS-1534)
> VBLOCKS-1534 | Stop using deprecated RTCIceCandidateStats

- CHANGELOG.md
- lib/twilio/call.ts
- tests/unit/call.ts
https://issues.corp.twilio.com/browse/VBLOCKS-1473
https://github.com/twilio/twilio-voice.js/issues/87
https://github.com/twilio/twilio-voice.js/issues/145
> VBLOCKS-1473 | Fix PeerConnection leak

- CHANGELOG.md
- lib/twilio/audiohelper.ts
- lib/twilio/shims/mediadevices.js
- tests/index.ts
- tests/shims/mediadevices.js
https://issues.corp.twilio.com/browse/VBLOCKS-1269
https://github.com/twilio/twilio-voice.js/issues/126
> VBLOCKS-1269 | Don't dispatch deviceinfochange indefinitely

- lib/twilio/device.ts
See https://issues.corp.twilio.com/browse/VBLOCKS-1538
> Updating documentation to prevent setRemoteDescription error

- .circleci/config.yml
This PR adds cron schedule in CircleCI to run tests and builds daily at 9:00am.
> Adding daily builds

- CHANGELOG.md
- browser/ws.js
- browser/xmlhttprequest.js
- lib/twilio/request.ts
- lib/twilio/wstransport.ts
- package-lock.json
- package.json
- tests/index.ts
- [VBLOCKS-1301](https://issues.corp.twilio.com/browse/VBLOCKS-1301)
* Remove `xmlhttprequest` package from dependency (use `fetch` instead)
* Move `ws` package to `devDependencies` (as it is required for unit tests)
> VBLOCKS-1301 Remove ws and xmlhttprequest dependencies.

- CHANGELOG.md
- lib/twilio/call.ts
- lib/twilio/device.ts
- package-lock.json
- tests/unit/call.ts
> VBLOCKS-1805 | Fix dtmf tones overrides

- CHANGELOG.md
- lib/twilio/audiohelper.ts
- lib/twilio/device.ts
- tests/unit/device.ts
- [CLIENT-0000](https://issues.corp.twilio.com/browse/CLIENT-0000)
This PR ensures that the enabled state persist during the lifetime of a Device instance.
Fixes #178
> fix(audio): Persist enabled sounds state

- lib/twilio.ts
- lib/twilio/audiohelper.ts
- lib/twilio/audioprocessor.ts
https://issues.corp.twilio.com/browse/VBLOCKS-2030
> VBLOCKS-2030 | API stubs and error checking

- CHANGELOG.md
- lib/twilio/call.ts
- tests/unit/call.ts
- [VBLOCKS-1690](https://issues.corp.twilio.com/browse/VBLOCKS-1690)
- Fix for https://github.com/twilio/twilio-voice.js/issues/163
A description of what this PR does.
> VBLOCKS-1690 Call reconnect() only when pstream is not null.

- lib/twilio/audiohelper.ts
- lib/twilio/audioprocessoreventobserver.ts
- lib/twilio/device.ts
- package-lock.json
- AudioProcessor Insights. See https://issues.corp.twilio.com/browse/VBLOCKS-2032.
- Using observer pattern with separate observable to separate public events (device.audio) vs internal (audio processor).
- Reusing audio helper instance, fixing a bug where calling device.updateOptions causes audio helper memory leak.
- Tests are no included. They are part of a separate ticket.
> VBLOCKS-2032 | AudioProcessor insights and reusing AudioHelper

- .circleci/config.yml
- lib/twilio/audiohelper.ts
- tests/audiohelper.js
- tests/index.ts
- tests/peerconnection.js
- tests/typecheck/audiohelper.ts
- tests/unit/audioprocessoreventobserver.ts
- tests/unit/call.ts
- tests/unit/device.ts
See VBLOCKS-2031 VBLOCKS-2412  for details.
> VBLOCKS-2031 VBLOCKS-2412 | Tests and Promise return type

- CHANGELOG.md
- lib/twilio/audiohelper.ts
- lib/twilio/audioprocessoreventobserver.ts
- lib/twilio/call.ts
- lib/twilio/device.ts
- lib/twilio/eventpublisher.ts
- lib/twilio/log.ts
- lib/twilio/outputdevicecollection.ts
- lib/twilio/preflight/preflight.ts
- lib/twilio/pstream.ts
- lib/twilio/rtc/peerconnection.ts
- lib/twilio/rtc/rtcpc.ts
- lib/twilio/wstransport.ts
- tests/eventpublisher.js
- tests/peerconnection.js
- tests/unit/log.ts
> VBLOCKS-1850 Add and improve debug logs

- COMMON_ISSUES.md
- tests/framework/README.md
- tests/framework/no-framework/README.md
- tests/framework/react/README.md
Fix client vs voice references
> Fix client vs voice references

- CHANGELOG.md
- lib/twilio/device.ts
- lib/twilio/util.ts
- tests/unit/device.ts
- tests/util.js
> VBLOCKS-2518 device.register() promise rejection

- CHANGELOG.md
- lib/twilio/errors/generated.ts
- package-lock.json
- package.json
- scripts/errors.js
- [VBLOCKS-2954](https://twilio-engineering.atlassian.net/browse/VBLOCKS-2954)
This PR updates the voice error dependency to the latest version and generates the new callmessageeventmessagetype error for use in the SDK.
> [VBLOCKS-2954] Update `@twilio/voice-errors` to `1.5.0`

- CHANGELOG.md
- lib/twilio/audiohelper.ts
- lib/twilio/rtc/peerconnection.ts
- package-lock.json
- tests/audiohelper.js
- tests/peerconnection.js
> VBLOCKS-3054 Fix echo and default stream not switching

- CHANGELOG.md
- lib/twilio/call.ts
- lib/twilio/device.ts
- package-lock.json
- tests/integration/callMessage/userDefinedMessage.ts
- tests/unit/call.ts
- tests/unit/device.ts
> VBLOCKS-3064 Move Call Message related errors to the Call object

- README.md
Per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources#sources -- the correct format for protocol source values has a trailing colon.
> Fix CSP in README.md

- CHANGELOG.md
- lib/twilio/audiohelper.ts
- tests/audiohelper.js
- tests/index.ts
- [VBLOCKS-3256](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3256)
Reference issue: https://github.com/twilio/twilio-voice.js/issues/228
- allow user to instantiate the Twilio Device after the permissions are set
- listen to microphone permission changes
Tested:
> [VBLOCKS-3256] Feat: listen for navigator permissions changes

- lib/twilio/audiohelper.ts
- tests/audiohelper.js
- [VBLOCKS-3375](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3375)
Permissions API not supported for Safari v15
> [VBLOCKS-3375] fix: check for navigator permissions

- CHANGELOG.md
- lib/twilio/device.ts
- package-lock.json
- tests/unit/device.ts
> VBLOCKS-3726 Use chunderw if present on reconnection

- .circleci/config.yml
- [VBLOCKS-4114](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4114)
This PR removes the relay server from the healthcheck workflow.
> [VBLOCKS-4114] Remove relay server from healthcheck

- CHANGELOG.md
- lib/twilio/preflight/preflight.ts
- tests/unit/preflight.ts
- [VBLOCKS-3932](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3932)
This PR adds the ability to pass a `chunderw` and `eventgw` to the internal `Twilio.Device` used in the `PreflightTest`. This API is not meant for public use, only for internal testing by Twilio employees.
This feature was tested locally using stage `chunderw` URI and a stage token.
> [VBLOCKS-3932] Add preflight stage capability

- CHANGELOG.md
- lib/twilio/audiohelper.ts
- tests/audiohelper.js
- tests/extension/app/popup/popup.html
- tests/extension/app/popup/popup.js
- tests/extension/app/worker.js
- tests/extension/tests/index.js
https://twilio-engineering.atlassian.net/browse/VBLOCKS-3973
- Issue: https://github.com/twilio/twilio-voice.js/issues/309
- Allow `device.destroy` in chrome extension
- remove enumeration check for `unbind`
- add unit test
- add puppeteer e2e test
> [VBLOCKS-3973] chrome extension destroy issue

- CHANGELOG.md
- lib/twilio/device.ts
- tests/unit/device.ts
- [VBLOCKS-4107](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4107)
This PR addresses an issue where the publisher is null upon device destruction.
Detailed explanation:
- When `device.destroy` is invoked, the signaling stream is destroyed first.
- This causes all the mediahandlers to close, issuing `PeerConnection._stopStream`
- In `_stopStream`, the default audio input stream is closed.
- However, in cases where audio processors are used, specifically if they are added after a call is started, the code path for a _selected_ audio input stream is used.
- `_stopStream` does _not_ …
> [VBLOCKS-4107] Fix null publisher on destroy

- .release.json
- package-lock.json
Fix release `development`, by adding `package-lock.json` to release plan
Only `package.json` was added back to `2.12.4-dev`, but `package-lock.json` still `2.12.4-rc1`
https://github.com/twilio/twilio-voice.js/commit/5d05caa5c57ca734056ec15fb0b2b9be8568567b#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R3
> fix: add package-lock.json to development

- CHANGELOG.md
- lib/twilio/call.ts
- lib/twilio/device.ts
- lib/twilio/rtc/peerconnection.ts
- tests/peerconnection.js
- tests/unit/call.ts
- tests/unit/device.ts
https://twilio-engineering.atlassian.net/browse/VBLOCKS-4478
- Fix Citrix MediaStream Error
- Added: [Device.Options.createMediaStream](https://twilio.github.io/twilio-voice.js/interfaces/voice.device.options.html#createMediaStream)
- `setInputDevice()` -> outgoing call
- `setInputDevice()` -> incoming call
> [VBLOCKS-4478] fix: citrix mediastream error

- lib/twilio.ts
- lib/twilio/audiohelper.ts
- lib/twilio/audioprocessor.ts
- lib/twilio/audioprocessoreventobserver.ts
- lib/twilio/call.ts
- lib/twilio/device.ts
- lib/twilio/errors/generated.ts
- lib/twilio/errors/index.ts
- lib/twilio/errors/twilioError.ts
- lib/twilio/outputdevicecollection.ts
- lib/twilio/preflight/preflight.ts
- lib/twilio/regions.ts
- scripts/errors.js
- [VBLOCKS-4564](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4564)
This PR adjusts the docstrings to comply with the new Typedoc specifications. Also, export previously non-exported members whose types are necessary for users.
> [VBLOCKS-4564] Typescript 5.x: fix docstrings and exports

- lib/twilio/rtc/rtcpc.ts
- lib/twilio/util.ts
- package-lock.json
- package.json
- tests/index.ts
- tests/unit/rtcpc.ts
- [VBLOCKS-4686](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4686)
This PR removes the `rtcpeerconnection-shim` library as it was only used for legacy edge, which our SDK has officially dropped support for.
> [VBLOCKS-4686] Remove rtcpeerconnectionshim
