CHANGELOG.md
lib/twilio/device.ts
tests/integration/device.ts
tests/integration/opus.ts
tests/integration/stirshaken.ts
tests/unit/device.ts

- [VBLOCKS-145](https://issues.corp.twilio.com/browse/VBLOCKS-145)
Remove `Device.activeCall` public class member.

Remove `Device.activeCall`.

---

package.json

- N/A
This PR updates the `ws` library dependency.

Update `ws` library.

---

CHANGELOG.md
README.md
package.json

This PR renames the 2.0.0 (Pilot) artifact to 2.0.0-preview.1 and prepares the repository to cut 2.0.0 (GA).

Fix versions

---

lib/twilio/device.ts

Copying over from our 1.14 commit https://github.com/twilio/twilio-client.js/issues/225

Cleanup listeners after destroy

---

lib/twilio/call.ts

Adds the missing event documentation per https://issues.corp.twilio.com/browse/VBLOCKS-184

Add Call#reconnected and Call#reconnecting doc blocks

---

package.json

Update ws version

---

CHANGELOG.md
lib/twilio/eventpublisher.js

https://github.com/twilio/twilio-client.js/issues/249

Stop throwing uncaught exceptions when Insights fails

---

CHANGELOG.md
lib/twilio/device.ts
tests/integration/device.ts
tests/unit/device.ts

- [VBLOCKS-331](https://issues.corp.twilio.com/browse/VBLOCKS-331)
This PR fixes the event signature and cleans up unused event timeouts.

[VBLOCKS-331] Fix `tokenWillExpire` event.

---

CHANGELOG.md
lib/twilio/device.ts
lib/twilio/pstream.js
lib/twilio/wstransport.ts
tests/eventtarget.js
tests/mock/WSTransport.js
tests/network/reconnection.ts
tests/pstream.js
tests/unit/device.ts
tests/unit/wstransport.ts

- [VBLOCKS-329](https://issues.corp.twilio.com/browse/VBLOCKS-329)
This PR propagates the connected edge to all internal SDK references after making a successful signaling connection.

[VBLOCKS-329] Update edge after successful connection.

---

tests/integration/device.ts
tests/integration/opus.ts

- [CLIENT-0000](https://issues.corp.twilio.com/browse/CLIENT-0000)
A description of what this PR does.

Fix integration test acceptance criteria.

---

tests/integration/preflight.ts

- N/A
This PR skips flaky tests.

Skip flaky integration tests.

---

lib/twilio/device.ts
lib/twilio/regions.ts
tests/unit/device.ts
tests/unit/regions.ts

- [VBLOCKS-418](https://issues.corp.twilio.com/browse/VBLOCKS-418)
This PR fixes the preferred URL that is set when the `stream#connected` event occurs.

[VBLOCKS-418] Fix WS URL.

---

package.json

- [CLIENT-0000](https://issues.corp.twilio.com/browse/CLIENT-0000)
Fixes #60

Support node versions higher than v12

---

CHANGELOG.md
lib/twilio/call.ts
lib/twilio/device.ts
tests/unit/call.ts

@mhuynh5757 Addresses the bug filed here: #34

GH34 | VBLOCKS-474

---

CHANGELOG.md
lib/twilio/eventpublisher.js
lib/twilio/pstream.js
lib/twilio/shims/mediadevices.js

#55 
Replaces `util.inherits` with new ES2015 `extends` syntax

GH55 VBLOCKS-470

---

lib/twilio/device.ts

Fixing broken constructors from the last PR that weren't caught by tests

Fix broken constructors

---

lib/twilio/device.ts

GH-34 | Fix ignore logic

---

tests/electron/main.js

- N/A
This PR redacts leaked credentials.

Redact leaked credentials

---

lib/twilio/call.ts
lib/twilio/device.ts
lib/twilio/rtc/peerconnection.js
tests/peerconnection.js
tests/unit/call.ts

- [VBLOCKS-505](https://issues.corp.twilio.com/browse/VBLOCKS-505)
This PR adds listeners and call events for SDK eventing.

[VBLOCKS-505] feat: sdk eventing; listener and event

---

lib/twilio/call.ts
lib/twilio/device.ts
lib/twilio/pstream.js
lib/twilio/uuid.ts
package-lock.json
package.json
tests/index.ts
tests/unit/call.ts
tests/unit/uuid.ts

- [VBLOCKS-1075](https://issues.corp.twilio.com/browse/VBLOCKS-1075)
This PR adds the send message API for SDK Eventing.

feat: send message api

---

CHANGELOG.md
lib/twilio/call.ts

Adding docs

---

CHANGELOG.md
lib/twilio/device.ts
package-lock.json
tests/unit/device.ts

This is an updated fix for https://github.com/twilio/twilio-voice.js/pull/121

VBLOCKS-1155 Make sure publisher host is inited if home region exists

---

CHANGELOG.md
lib/twilio/call.ts

Adding changelog draft

---

lib/twilio/errors/generated.ts
package-lock.json
package.json
templates/constants.js

Adding 31209 error for max payload size limit. Below is the screenshot for the error received from the SDK

VBLOCKS-1218 Adding 31209 error for max payload size limit

---

CHANGELOG.md
lib/twilio/call.ts
lib/twilio/errors/generated.ts
lib/twilio/uuid.ts
package-lock.json
package.json

Prep for release

---

CHANGELOG.md

Add 2.3.1 changelog entry. cc @kamalbennani

Add 2.3.1 changelog entry

---

CHANGELOG.md
lib/twilio/device.ts
tests/unit/device.ts

This is from @SiimMardus and @ostap0207 PRs with my review suggestion and a changelog.
https://github.com/twilio/twilio-voice.js/pull/143
https://github.com/twilio/twilio-voice.js/pull/106

GH95 | error is not returned when mic access is blocked

---

lib/twilio/audiohelper.ts
lib/twilio/call.ts
lib/twilio/device.ts
lib/twilio/log.ts
lib/twilio/rtc/peerconnection.js
lib/twilio/rtc/rtcpc.js
lib/twilio/rtc/stats.js
tests/unit/device.ts

VDI Support 2.x initial implementation. Taken from [1.x](https://github.com/twilio/twilio-client.js/pull/313/files). Changelog, tests, and documentation will be part of a seperate ticket.

VDI Support 2.x initial implementation

---

.circleci/config.yml
lib/twilio/audiohelper.ts
lib/twilio/call.ts
package.json

Other build checks are not part of CI which sometimes caused our release process to fail and harder to debug. This PR adds those checks.

Adding build checks to the ci pipeline

---

CHANGELOG.md

Changelog for 2.0.6

---

tests/integration/device.ts

Adjust flaky test

---

lib/twilio/uuid.ts

- [VBLOCKS-1980](https://issues.corp.twilio.com/browse/VBLOCKS-1980)
A description of what this PR does.

VBLOCKS-1980 If md5 is exported as a default, then use it.

---

CHANGELOG.md

Add 2.7.1 changelog

---

CHANGELOG.md
lib/twilio/call.ts
lib/twilio/device.ts

Fixed missing documentation for some events

VBLOCKS-2175 | Fix events docs

---

package-lock.json
package.json

N/A
Bump version for feature branch `feature/error-codes`.

chore: bump versions

---

lib/twilio.ts
lib/twilio/audiohelper.ts
lib/twilio/audioprocessor.ts
lib/twilio/call.ts
lib/twilio/device.ts
lib/twilio/rtc/peerconnection.ts
package-lock.json
tests/peerconnection.js
tests/unit/call.ts

AudioProcessor implementation. See https://issues.corp.twilio.com/browse/VBLOCKS-2180

VBLOCKS-2180 | AudioProcessor implementation

---

CHANGELOG.md

Update 2.7.2 CHANGELOG.md to reflect Sonoma issue.

Update 2.7.2 CHANGELOG.md to reflect Sonoma issue.

---

CHANGELOG.md
lib/twilio/audiohelper.ts
lib/twilio/audioprocessoreventobserver.ts
lib/twilio/call.ts
lib/twilio/device.ts
lib/twilio/eventpublisher.ts
lib/twilio/log.ts
lib/twilio/outputdevicecollection.ts
lib/twilio/preflight/preflight.ts
lib/twilio/pstream.ts
lib/twilio/rtc/peerconnection.ts
lib/twilio/rtc/rtcpc.ts
lib/twilio/wstransport.ts
tests/eventpublisher.js
tests/peerconnection.js
tests/unit/log.ts

VBLOCKS-1850 Add and improve debug logs (merge feature branch)

---

CHANGELOG.md
lib/twilio/device.ts
tests/unit/device.ts

VBLOCKS-1559 Fix InvalidState error after updating token

---

CHANGELOG.md
lib/twilio/audiohelper.ts
lib/twilio/audioprocessoreventobserver.ts
lib/twilio/device.ts
tests/audiohelper.js
tests/typecheck/audiohelper.ts
tests/unit/audioprocessoreventobserver.ts
tests/unit/device.ts

VBLOCKS-2559 AudioProcessor enabled event

---

CHANGELOG.md
lib/twilio/call.ts
lib/twilio/device.ts
lib/twilio/rtc/peerconnection.ts
lib/twilio/rtc/rtcpc.ts
package-lock.json
tests/integration/deviceOptions.ts
tests/peerconnection.js
tests/unit/call.ts

VBLOCKS-1118 Fix rtcConstraints error

---

CHANGELOG.md
lib/twilio/pstream.ts
tests/pstream.js

This is the same approved PR https://github.com/twilio/twilio-voice.js/pull/240

VBLOCKS-2605 Signaling reconnectTimeout parameter

---

lib/twilio/call.ts
lib/twilio/device.ts
tests/unit/call.ts

- [VBLOCKS-1009](https://issues.corp.twilio.com/browse/VBLOCKS-1009)
Add insights events to callmessage sent/received/error

[VBLOCKS-1009] feat: publish insights events

---

lib/browser.js
lib/twilio/call.ts
lib/twilio/device.ts
lib/twilio/rtc/peerconnection.ts
lib/twilio/wstransport.ts

See https://docs.google.com/document/d/1QMwkNXlJYSANksP0BrlJ_JAbJA86x85ZKKQ8656GnUw/edit#heading=h.woffqrxm0odm
// TODO (different tickets)
- changelog
- tests

VBLOCKS-2929 VBLOCKS-2927 Manual reconnection API

---

lib/twilio/call.ts

VBLOCKS-2832 Send reconnect flag to insights

---

.circleci/config.yml
CHANGELOG.md
lib/twilio/call.ts
lib/twilio/device.ts

Changelog and skip test for RC

Changelog and skip test for RC

---

CHANGELOG.md
lib/twilio/device.ts

Improve docs

---

lib/twilio/device.ts

Copying docs from devEd https://github.com/twilio-internal/docs/pull/1911

Update maxCallSignalingTimeoutMs docs from devEd

---

CHANGELOG.md
lib/twilio/audiohelper.ts
lib/twilio/device.ts
tests/audiohelper.js
tests/unit/device.ts

See VBLOCKS-2716 and changelog

VBLOCKS-2716 Error when calling setInputDevice then connect

---

CHANGELOG.md
lib/twilio/errors/generated.ts
package-lock.json
package.json
scripts/errors.js

See VBLOCKS-3141 and changelog

VBLOCKS-3141 Update 31209 and 31212 errors

---

CHANGELOG.md
lib/twilio/preflight/preflight.ts
tests/unit/preflight.ts

VBLOCKS-3257 Handle missing rtcIceCandidateStatsReport

---

PREFLIGHT.md
lib/twilio/preflight/preflight.ts

VBLOCKS-3365 Update preflight docs

---

CHANGELOG.md
PREFLIGHT.md
lib/twilio/audiohelper.ts
lib/twilio/preflight/preflight.ts
tests/audiohelper.js
tests/index.ts
tests/unit/preflight.ts

- N/A
This PR is a merge commit that pulls main into the eventing 1.5 feature branch.
The following commands were run:
```
git checkout master
git pull
git checkout feature/eventing_1.5
git pull
git checkout -b task/merge-main-into-eventing-1.5-feature-branch
git merge master
```

Merge main into eventing 1.5 feature branch

---

CHANGELOG.md

- [CLIENT-0000](https://issues.corp.twilio.com/browse/CLIENT-0000)
A description of what this PR does.

update: 2.12.0 changelog

---

tests/audiohelper.js
tests/index.ts

- [VBLOCKS-3750](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3750)
- fix navigator tests node22
- [globalThis.navigator](https://github.com/nodejs/node/issues/39540#issuecomment-1770612761) added in Node v22
- Tested locally node v22.8.0

[VBLOCKS-3750] Fix: tests navigator

---

.circleci/config.yml
package-lock.json
package.json
tests/extension/app/offscreen/offscreen.js
tests/extension/app/popup/popup.js
tests/extension/app/worker.js
tests/extension/tests/index.js

- [VBLOCKS-3227](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3227)
Implement extension e2e in chrome

[VBLOCKS-3227] ci extension e2e

---

tests/extension/tests/index.js

[VBLOCKS-3931](https://twilio-engineering.atlassian.net/browse/VBLOCKS-3931)
- Add executable path for puppeteer tests
- https://pptr.dev/guides/configuration

[VBLOCKS-3931] add executable path puppeteer

---

.circleci/config.yml
tests/extension/tests/index.js

- https://twilio-engineering.atlassian.net/browse/VBLOCKS-3925
Adds mocha tests to datadog

[VBLOCKS-3925] feat: dd-trace

---

.release.json
package-lock.json
package.json

https://twilio-engineering.atlassian.net/browse/VBLOCKS-3863
Update latest version of release tool
https://www.npmjs.com/package/twilio-release-tool
https://github.com/twilio/release-tool

[VBLOCKS-1719] chore: update latest release tool

---

README.md

[VBLOCKS-4150](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4150)
Add Reference components to readme
* [] Updated CHANGELOG.md if necessary
* [] Added unit tests if necessary
* [] Verified locally with `npm test`
* [] Manually sanity tested running locally

[VBLOCKS-4150] chore: add reference components to readme

---

.circleci/config.yml
.gitignore
.npmignore
karma.conf.ts
package-lock.json
package.json

- https://twilio-engineering.atlassian.net/browse/VBLOCKS-4237
[Branch DD Dashboard](https://app.datadoghq.com/ci/test/repositories/github.com%2Ftwilio%2Ftwilio-voice.js/all-services/VBLOCKS-4237-e2e-datadog?query=test_level%3Asuite%20env%3Aci%20%40git.repository.id%3Agithub.com%2Ftwilio%2Ftwilio-voice.js%20%40git.branch%3AVBLOCKS-4237-e2e-datadog&colorBy=meta%5B%27_dd.ci.test_level%27%5D&colorByAttr=meta%5B%27_dd.ci.test_level%27%5D&currentTab=overview&env=ci&eventStack=&fromUser=false&graphType=flamegraph&index=citest&spanViewType=networks&start=1741805818296&end=1742420748867&paused=false …

[VBLOCKS:4237] feat: upload integration tests to Datadog

---

lib/twilio/device.ts
lib/twilio/preflight/preflight.ts
lib/twilio/statsMonitor.ts

- [VBLOCKS-4564](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4564)
This PR modifies the SDK code to compile when using TS 5.x.

[VBLOCKS-4564] Typescript 5.x: get SDK to compile

---

tests/unit/preflight.ts
tests/unit/statsMonitor.ts

- [VBLOCKS-4564](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4564)
This PR modifies the test files to compile using Typescript 5.x.

[VBLOCKS-4564] Typescript 5.x: test files

---

CHANGELOG.md
package-lock.json
package.json

- [VBLOCKS-4564](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4564)
This PR simply does `git merge master` in the `feature/upgrade-typescript-4.x-to-5.x` branch.

[VBLOCKS-4564] Merge master into Typescript upgrade feature branch

---

COMMON_ISSUES.md

- [VBLOCKS-4685](https://twilio-engineering.atlassian.net/browse/VBLOCKS-4685)
This PR adds a note to our `COMMON_ISSUES.md` file about building Angular apps using our SDK.

[VBLOCKS-4685] docs: add note to common issues about commonjs deps

---

.circleci/config.yml

- Update qe tests trigger
- Update circleci personal token env variable
- Add additional pipeline param to trigger qe tests separately
- [QSDK-10853](https://twilio-engineering.atlassian.net/browse/QSDK-10853)
All QE Tests was moved to twilio-internal and QE Tests trigger needs to be updated

QSDK-10853: Update triggers in SDK CCI jobs to twilio-internal

---

.circleci/config.yml
package-lock.json
package.json

https://twilio-engineering.atlassian.net/browse/VBLOCKS-5118
- CI Pipeline is currently failing for unit tests
- upgrade mocha version fixes issue

[VBLOCKS-5118] chore: upgrade mocha version

---

.circleci/config.yml
package-lock.json
package.json
tests/extension/tests/index.js

https://twilio-engineering.atlassian.net/browse/VBLOCKS-5144
- Upgrade puppeteer version

[VBLOCKS-5144] Fix puppeteer

---

package.json

This PR fixes the filenames of the import paths.

[VBLOCKS-5243] Rollup fix import paths

---

CHANGELOG.md

This PR sets the changelog release date for `2.16.0`.

Set `CHANGELOG.md` release date for `2.16.0` release
